Translation = {
    -- IDENTITY
    ['fr'] = {
        ['select_character'] = 'Mon personnage',
        ['select_character_desc'] = '~b~Choisisez un personnage.',
        ['new_character'] = '~b~Créer nouveau personnage',
        ['new_character_desc'] = 'Créer nouveau personnage.',
        ['slots_full'] = 'Pas assez d\'emplacement de personnage!',

        ['select_title'] = 'Enregistrement',
        ['last_position'] = '~b~→ ~s~dernière position',
        ['position_desc'] = 'Cliquez pour apparaître à ~b~',
        ['position_desc_2'] = '~s~.',    
        
        ['register_title'] = 'Créer personnage',
        ['register_title_desc'] = 'Completez votre carte d\'identité!',
        ['gender_m'] = ' Masculin ',
        ['gender_f'] = ' Féminin ',
        ['name'] = 'Prénom',
        ['lastname'] = 'Nom de famille',
        ['dob'] = 'Date de naissance',
        ['height'] = 'Taille',
        ['sex'] = 'Sexe',
        ['confirm'] = '~b~Entrer sur l\'île',
        ['confirm_desc'] = 'Tout est correct?',
        ['insert_name'] = 'Entrer prénom',
        ['insert_lastname'] = 'Entrer nom de famille',
        ['insert_dob'] = 'Entrer date de naissance (exemple: 01.01.2000)',
        ['insert_height'] = 'Entrer votre taille (140-200)',
        ['height_unit'] = 'cm',
        ['register_error'] = '~r~Au moins un champ n\'est pas correct!',

        ['ped_models'] = 'Modèles de personnage',
        ['default_ped'] = 'Personnage par défaut',
        ['pedmode_no_perms'] = '~r~Vous ne pouvez pas faire ça!',

        ['enter_char'] = 'Entrer',
        ['delete_char'] = '~r~Supprimer personnage',
        ['delete_char_confirm'] = '~r~Confirmation de suppression',

        ['giveperm_wrong_usage'] = '~r~Usage incorrect! ~w~/giveperm [Player-ID] [charamount/pedmode] [Value]',
        ['giveperm_success'] = '~g~Ajout des permissions réussie',
        ['giveperm_error'] = '~r~Joueur hors-ligne!',
    },

    -- CREATOR

    ['fr'] = {
        ['face_title'] = 'Votre personnage',
        ['male'] = 'Masculin',
        ['female'] = 'Féminin',
        ['sex'] = 'Sexe',
        ['parents'] = 'Parents',
        ['mother'] = 'Mère',
        ['father'] = 'Père',
        ['similarity'] = 'Similarité',
        ['complexion'] = 'Complexité',
        ['ageing'] = 'Effets d\'âge',
        ['ageing_intensity'] = 'Intensité des effets d\'âge',
        ['eyecolour'] = 'Couleur des yeux',
        ['eyebrows'] = 'Sourcils',
        ['eyebrows_intensity'] = 'Intensité des sourcils',
        ['complexion'] = 'Défauts',
        ['complexion_intensity'] = 'Intensité des défauts',
        ['sun_damage'] = 'Taches de rousseur',
        ['sun_damage_intensity'] = 'Intensité des taches de rousseur',
        ['change_colour'] = 'Changement de couleur',
        ['change_variation'] = 'Changer variation',
    },

    -- DRUGS

    ['fr'] = {
        ['access_computer'] = 'Press ~g~E~s~, to access the computer',
        ['enter_farm'] = 'Press ~g~E~s~, to enter ~o~',
        ['enter_farm_2'] = '~s~.',
        ['leave_farm'] = 'Press ~g~E~s~, to leave the farm',

        ['nothing_produced'] = '~y~Nothing could be produced in your absence as there are no supplies.',
        ['successfully_produced'] = '~g~During your absence, ~w~',
        ['successfully_produced_2'] = '~g~were produced.',
        ['successfully_produced_3'] = ' ~g~produced.',
        ['successfully_produced_storageEmpty'] = ' ~g~produced. Supplies are empty!',

        ['get_from_storage'] = '~s~ taken from the warehouse.',
        ['farm_bought_title'] = 'Farm bought',
        ['farm_bought'] = 'Well! ~g~',
        ['farm_bought_2'] = ' ~s~is now yours. Good choice!',

        ['weed'] = '~g~Weed',
        ['meth'] = '~b~Meth',
        ['coke'] = '~w~Coke',

        ['supplies'] = 'Supplies',
        ['already_started_mission'] = '~r~You have already started a mission!',
        ['notEnoughMoney'] = '~r~Not enough money!',

        ['mission_car_changed'] = 'You new vehicle ~y~',
        ['mission_car_changed_2'] = ' ~s~is being delivered.',
        ['mission_startLoading'] = 'Hee! You have to be here to pick up the supplies. We start loading.',
        ['mission_seller'] = 'Seller',
        ['mission_outofrange'] = '~y~The vehicle could not be fully loaded. Return to the seller!',
        ['mission_loading'] = 'Vehicle is being loaded: \n~g~',
        ['mission_loading_2'] = '% ~s~completed.',
        ['mission_wrongCar'] = 'I guess this vehicle is not the right one..',
        ['mission_backToFarm'] = 'Drive back to your farm!',

        ['mission_self_plants_bought'] = 'x supplies ~s~bought for ~g~',
        ['mission_self_plants_bought_2'] = '$~s~.',
        ['mission_self_plants_notEnoughMoney'] = 'The supplies were ~r~unloaded~s~, because you do not have enough money!.',
        ['mission_dou_plants_bought'] = 'x supplies ~s~were ~g~bought ~s~by your boss.',
        ['mission_dou_plants_abort'] = '~b~',
        ['mission_dou_plants_abort_2'] = '~s~s Mission was ~r~canceled~s~, because you do not have enough money.',
        ['mission_dou_plants_abort_target'] = 'Mission was ~r~aborted~s~, because the supplies were not paid for.',
        ['mission_dou_plants_arrived'] = 'The delivery with ~g~',
        ['mission_dou_plants_arrived_2'] = ' supplies arrived at this moment.',
        ['mission_dou_plants_arrived_target'] = 'Supplies successfully ~g~delivered',

        ['mission_press_e_deliver'] = 'Press ~g~E~s~, to unload the supplies',
        ['mission_wrongCar_deliver'] = 'This is not the vehicle we have loaded?',

        ['mission_invited'] = 'You were ~g~invited ~s~to do a ~b~mission~s~. Press  ~g~E~s~, to accept.',
        ['mission_invited_over'] = 'The invite has ~r~expired~s~!',

        ['menu_enter_farm'] = 'Enter the farm',
        ['menu_buy_farm'] = 'Buy the farm',
        ['menu_buy_name'] = 'Name:',
        ['menu_buy_type'] = 'Type:',
        ['menu_buy_price'] = 'Price:',
        ['menu_buy_confirm'] = 'Confirm',

        ['menu_computer_level'] = 'Level ',
        ['menu_computer_produced'] = 'Finished drugs',
        ['menu_computer_produced_desc'] = 'Finished and packed drugs',
        ['menu_computer_storage'] = 'Supplies',
        ['menu_computer_storage_desc'] = 'Supplies are needed for the production',
        ['menu_computer_takedrugs'] = 'How much should be withdrawn?',
        ['menu_computer_notenoughdrugs'] = 'You do not have that much in stock!',

        ['menu_storage'] = 'Get supplies',
        ['menu_storage_input'] = 'Store supplies',
        ['menu_storage_input_desc'] = 'Store supplies you have in your inventory',
        ['menu_storage_storageLimit'] = '~s~There is only space left for ~y~',
        ['menu_storage_storageLimit_2'] = ' supplies~s~!',
        ['menu_storage_notenough'] = '~r~You do not have enough supplies!',
        ['menu_storage_buy'] = 'Buy supplies',
        ['menu_storage_buy_desc'] = 'Buy supplies from black market',
        ['menu_storage_buy_self'] = 'Buy supplies on your own',
        ['menu_storage_buy_others'] = 'Let somebody buy your supplys',
        ['menu_storage_buy_others_desc'] = 'The person have to stay next to the farm entrance',
        ['menu_storage_inputseeds'] = 'How much should be stored?',
        ['storagemission_invite'] = 'Click to ask ~b~',
        ['storagemission_invite_2'] = '~s~',

        ['menu_upgrade'] = 'Upgrade farm',
        ['menu_upgrade_prod'] = 'Improve farm',
        ['menu_upgrade_prod_desc'] = 'Increase productivity and storage',
        ['menu_upgrade_prod_level2'] = 'Improve equipment',
        ['menu_upgrade_prod_level2_desc'] = 'Increase performance by improving your equipment: e.g. better fans',
        ['menu_upgrade_prod_level3'] = 'Improve security',
        ['menu_upgrade_prod_level3_desc'] = 'Increase performance by improving your monitoring: e.g. Video recording',
        ['menu_upgrade_level2required'] = 'Level 2 required',
        ['upgraded_title'] = 'Buy upgrade',
        ['upgraded'] = 'The ~y~level ~s~of your farm was upgraded to ~y~',
        ['upgraded_2'] = ' ~s~. Reenter the farm to see the progress.',

        ['menu_stats_finished'] = '~b~Storage capacity (finished drugs):',
        ['menu_stats_storecap'] = '~b~Storage capacity (supplies):',
        ['menu_stats_storecap_desc'] = '~s~4x supplies = 1x drug',
        ['menu_stats_productivity'] = '~b~Production speed',

        ['menu_changeVehicle'] = 'Change mission vehicle',
        ['menu_changeVehicle_change'] = 'Click to select ~b~',
        ['menu_changeVehicle_change2'] = ' ~s~as your mission vehicle',

        ['menu_access'] = 'Key cards',
        ['menu_access_desc'] = 'Set up who have access to the farm',
        ['menu_access_trust_remove'] = 'Click to revoke ~b~',
        ['menu_access_trust_remove_2'] = ' ~s~s access',
        ['menu_addTrusted'] = '~g~Grant access',
        ['menu_access_trust_add'] = 'Click to grant ~b~',
        ['menu_access_trust_add_2'] = ' ~s~access',

        ['menu_access_removed'] = ' ~s~s access was revoked.',
        ['menu_access_removed_target'] = 'You access for ~y~farm (#',
        ['menu_access_removed_target_2'] = ') was revoked.',
        ['menu_access_granted'] = ' ~s~s access was granted.',
        ['menu_access_granted_target'] = 'You now have access to ~g~farm (#',
        ['menu_access_granted_target_2'] = ')',
    },

    -- CAR 

    ['fr'] = {
        ['ring_infobar'] = 'Press ~b~E~s~ to notify a cardealer',
        ['showroom_infobar'] = 'Press ~b~E~w~, to access the ~o~Showroom~w~!',
        ['boss_infobar'] = 'Press ~b~E~w~, to access the ~o~Boss Menü~w~!',
        ['wardrobe_infobar'] = 'Press ~b~E~w~, to access the ~o~wardrobe~w~!',
        ['garage_infobar'] = 'Press ~b~E~w~, to access the ~o~garage~w~!',
        ['computer_infobar'] = 'Press ~b~E~w~, to access the ~o~Computer~w~!',
        ['delete_vehicle'] = 'Press ~b~E~w~, to ~o~store the vehicle~w~!',
        ['wardrobe'] = 'Wardrobe',
        ['private_clothes'] = 'Private clothes',
        ['bossmenu'] = 'Boss Menu',
        ['finance_management'] = 'Financial management',
        ['staff'] = 'Staff management',
        ['society_money'] = 'Society money',
        ['withdraw_money'] = 'Withdraw money',
        ['deposit_money'] = 'Deposit money',
        ['withdraw_desc'] = 'Do you want to ~g~withdraw~w~ money?',
        ['deposit_desc'] = 'Do you want to ~g~deposit~w~ money?',
        ['how_much'] = 'How much?',
        ['company_money'] = 'Society money',
        ['unknown_amount'] = '~r~Invlaid amount!',
        ['deposit_msg'] = 'You deposited ~g~',
        ['deposit_msg2'] = ' $~w~',
        ['withdraw_msg'] = 'You have withdrawn ~g~',
        ['withdraw_msg2'] = ' $~w~ from your society',
        ['hire'] = 'Hire somebody',
        ['staff_management'] = 'Staff management',
        ['job_rank'] = 'Job rank:',
        ['fire'] = '~r~Fire',
        ['fire_msg'] = 'Do you want to fire ~b~',
        ['fire_msg2'] = '~w~?',
        ['promote'] = 'Promote',
        ['promote_msg'] = 'Do you want to promote ~b~',
        ['promote_msg2'] = '~w~ to ~b~',
        ['promote_msg3'] = ' ~w~?',
        ['showroom'] = 'Showroom',
        ['change_color'] = '~b~Change color',
        ['primary_color'] = 'Primary color',
        ['primary_color_msg'] = 'Set as primary color',
        ['secondary_color'] = 'Secondary color',
        ['secondary_color_msg'] = 'Set as secondary color',
        ['pearl'] = 'Pearlescent',
        ['pearl_msg'] = 'Set as pearlescent',
        ['show_manufacturer'] = 'Manufacturer:',
        ['show_price'] = 'Price:',
        ['show_model'] = 'Model:',
        ['show_park_item'] = 'Exhibit at Showroom',
        ['show_performance'] = 'Performance:',
        ['show_maxSpeed'] = 'Max. speed:',
        ['show_speedup'] = 'Speedup 0-100:',
        ['show_modifications'] = 'Amount of modifications:',
        ['show_fuelcapacity'] = 'Fuel capacity:',
        ['show_suffix_performance'] = ' PS',
        ['show_suffix_maxSpeed'] = ' mp/h',
        ['show_suffix_speedup'] = ' seconds',
        ['show_suffix_modifications'] = ' parts',
        ['show_suffix_fuelcapacity'] = ' l',
        ['test_drive'] = '~b~Prepare for a test drive',
        --['amount_cardealer'] = 'Stock in cardealership:',
        ['amount_storage'] = 'Stock in warehouse:',
        ['set_to_showroom'] = 'Exhibit at Showroom',
        ['amount_cars'] = 'Cars available',
        ['computer'] = 'Computer',
        ['sell_vehicle'] = 'Sell vehicle',
        ['show_1'] = 'Showroom 1',
        ['show_2'] = 'Showroom 2',
        ['show_3'] = 'Showroom 3',
        ['show_4'] = 'Showroom 4',
        ['show_abort'] = '~r~Abort',
        ['yes'] = 'Yes',
        ['no'] = 'No',
        ['car_sell'] = ' (Press to sell)',
        ['bill_purchase_of'] = 'Purchase of a ',
        ['dialog_price'] = 'Price',
        ['no_customers'] = '~o~There is no customer next to you! There have to be a customer next to you to sell a car.',
        ['vehicles_list'] = 'Vehicles',
        --['car_deliver'] = 'Bring this car to the dealership: ',
        ['car_craft'] = 'Order this vehicle: ',
        ['amount'] = 'Amount',
        --['ordered'] = 'Ordered: ',
        ['reserved'] = 'Ordered: ',
        ['orders'] = 'Orders',
        ['total_production_time'] = 'Remaining production time:',
        ['current_production_time'] = 'Ordered vehicles:',
        ['refresh_time'] = 'Refresh',
        ['hours'] = ' hours',
        ['hired'] = '~g~Hired~w~!',
        ['you_were_hired'] = 'You were ~g~hired!~w~',
        ['you_hired'] = 'You ~g~hired ~b~',
        ['you_hired2'] = '~g~~w~!',
        ['already_hired'] = '~r~Already hired!~w~',
        ['is_already_hired'] = ' is already ~r~hired~w~!',
        ['fired'] = '~r~Fired~w~!',
        ['you_are_fired'] = 'You were ~r~fired~w~!',
        ['you_fired'] = 'You ~r~fired ~b~',
        ['you_fired2'] = '~r~~w~!',
        ['error'] = '~r~Error~w~!',
        ['player_not_online'] = 'This ~b~player~w~ is not online!',
        ['promoted'] = '~g~Promoted~w~!',
        ['you_were_promoted'] = 'You were ~b~promoted ~s~to~b~',
        ['you_were_promoted2'] = '~g~~w~!',
        ['you_promoted'] = 'You ~b~promoted ~b~',
        ['you_promoted2'] = '~w~ to ~b~',
        ['you_promoted3'] = '~g~~w~!',
        ['ring_ring'] = '~b~There is a ~w~customer waiting ~b~at the dealership!',
        ['vehicle_purchased'] = '~g~Vehicle purchased~w~!',
        ['you_purchased'] = 'You got a ',
        ['you_purchased2'] = ', with the number plate ',
        ['you_purchased3'] = ' ~g~',
        ['vehicle_sold'] = '~g~Vehicle sold~w~!',
        ['you_sold'] = 'You sold a ',
        ['you_sold2'] = ' ~g~',
        ['vehicle_ordered'] = '~g~Vehicle ordered~w~!',
        ['you_ordered'] = 'You ~g~ordered ',
        ['you_ordered2'] = ' ~s~. In total you ~g~ordered ',
        ['you_ordered3'] = 'x ~s~!',
        ['you_applied'] = 'You ~g~ordered ',
        ['you_applied2'] = ' ~s~. In total you ~g~ordered ',
        ['you_applied3'] = '~s~.',
        ['not_enough_money'] = 'There is ~r~not enough money~s~ on your society wallet!',
        ['vehicle_delivered'] = 'Vehicles ~g~successfully delivered~s~!',
        ['not_enough_vehicles_in_storage'] = 'There are not enough vehicles in the large warehouse',
        ['presented_prefix'] = '~y~Displayed: ~s~',
        ['insert_new_value'] = 'Insert a new value',
        ['click_to_change'] = '~b~click to change the value',
        ['not_enough_money_player'] = '~r~Not enough money!',
        ['required_order_time'] = 'Required manufacturing time:',
		['customer_not_enough_money'] = '~r~The customer does not have enough money!',
    },

}