Translation = {
    -- IDENTITY
    ['fr'] = {
        ['select_character'] = 'Mon personnage',
        ['select_character_desc'] = '~b~Choisisez un personnage.',
        ['new_character'] = '~b~Créer nouveau personnage',
        ['new_character_desc'] = 'Créer nouveau personnage.',
        ['slots_full'] = 'Pas assez d\'emplacement de personnage!',

        ['select_title'] = 'Enregistrement',
        ['last_position'] = '~b~→ ~s~dernière position',
        ['position_desc'] = 'Cliquez pour apparaître à ~b~',
        ['position_desc_2'] = '~s~.',    
        
        ['register_title'] = 'Créer personnage',
        ['register_title_desc'] = 'Completez votre carte d\'identité!',
        ['gender_m'] = ' Masculin ',
        ['gender_f'] = ' Féminin ',
        ['name'] = 'Prénom',
        ['lastname'] = 'Nom de famille',
        ['dob'] = 'Date de naissance',
        ['height'] = 'Taille',
        ['sex'] = 'Sexe',
        ['confirm'] = '~b~Entrer sur l\'île',
        ['confirm_desc'] = 'Tout est correct?',
        ['insert_name'] = 'Entrer prénom',
        ['insert_lastname'] = 'Entrer nom de famille',
        ['insert_dob'] = 'Entrer date de naissance (exemple: 01.01.2000)',
        ['insert_height'] = 'Entrer votre taille (140-200)',
        ['height_unit'] = 'cm',
        ['register_error'] = '~r~Au moins un champ n\'est pas correct!',

        ['ped_models'] = 'Modèles de personnage',
        ['default_ped'] = 'Personnage par défaut',
        ['pedmode_no_perms'] = '~r~Vous ne pouvez pas faire ça!',

        ['enter_char'] = 'Entrer',
        ['delete_char'] = '~r~Supprimer personnage',
        ['delete_char_confirm'] = '~r~Confirmation de suppression',

        ['giveperm_wrong_usage'] = '~r~Usage incorrect! ~w~/giveperm [Player-ID] [charamount/pedmode] [Value]',
        ['giveperm_success'] = '~g~Ajout des permissions réussie',
        ['giveperm_error'] = '~r~Joueur hors-ligne!',
    },

    -- CREATOR

    ['fr'] = {
        ['face_title'] = 'Votre personnage',
        ['male'] = 'Masculin',
        ['female'] = 'Féminin',
        ['sex'] = 'Sexe',
        ['parents'] = 'Parents',
        ['mother'] = 'Mère',
        ['father'] = 'Père',
        ['similarity'] = 'Similarité',
        ['complexion'] = 'Complexité',
        ['ageing'] = 'Effets d\'âge',
        ['ageing_intensity'] = 'Intensité des effets d\'âge',
        ['eyecolour'] = 'Couleur des yeux',
        ['eyebrows'] = 'Sourcils',
        ['eyebrows_intensity'] = 'Intensité des sourcils',
        ['complexion'] = 'Défauts',
        ['complexion_intensity'] = 'Intensité des défauts',
        ['sun_damage'] = 'Taches de rousseur',
        ['sun_damage_intensity'] = 'Intensité des taches de rousseur',
        ['change_colour'] = 'Changement de couleur',
        ['change_variation'] = 'Changer variation',
    },

    -- DRUGS

    ['fr'] = {
        ['access_computer'] = 'Appuyez sur ~g~E~s~, pour accéder à l\'ordinateur.',
        ['enter_farm'] = 'Appuyez sur ~g~E~s~, pour entrer ~o~',
        ['enter_farm_2'] = '~s~.',
        ['leave_farm'] = 'Appuyez sur ~g~E~s~, pour quitter la ferme.',

        ['nothing_produced'] = '~y~Rien n\'a été produit en votre absence par manque de ressources.',
        ['successfully_produced'] = '~g~Pendant votre absence, ~w~',
        ['successfully_produced_2'] = '~g~a été produit.',
        ['successfully_produced_3'] = ' ~g~produit.',
        ['successfully_produced_storageEmpty'] = ' ~g~produit. Plus assez de matières premières!',

        ['get_from_storage'] = '~s~ pris de l\'entrepôt.',
        ['farm_bought_title'] = 'Ferme achetée',
        ['farm_bought'] = 'Bien! ~g~',
        ['farm_bought_2'] = ' ~s~vous appartient. Bon choix!',

        ['weed'] = '~g~Marijuana',
        ['meth'] = '~b~Meth',
        ['coke'] = '~w~Cocaïne',

        ['supplies'] = 'Matières premières',
        ['already_started_mission'] = '~r~Vous avez déjà lancé une mission!',
        ['notEnoughMoney'] = '~r~Pas assez d\'argent!',

        ['mission_car_changed'] = 'Votre nouveau véhicule ~y~',
        ['mission_car_changed_2'] = ' ~s~est en cours de livraison.',
        ['mission_startLoading'] = 'Hey! Tu dois être là pour ramasser les matières premières. On commence le chargement.',
        ['mission_seller'] = 'Vendeur',
        ['mission_outofrange'] = '~y~Le véhicule n\'a pas pu être complètement chargé. Retourne au vendeur!',
        ['mission_loading'] = 'Vehicule en cours de remplissage: \n~g~',
        ['mission_loading_2'] = '% ~s~completé.',
        ['mission_wrongCar'] = 'Ce n\'est pas le bon véhicule..',
        ['mission_backToFarm'] = 'Retourne à ta ferme!',

        ['mission_self_plants_bought'] = 'x matière premières ~s~achetées for ~g~',
        ['mission_self_plants_bought_2'] = '$~s~.',
        ['mission_self_plants_notEnoughMoney'] = 'Les marchandises on été ~r~déchargées~s~, parce que tu n\'a pas assez d\'argent!.',
        ['mission_dou_plants_bought'] = 'x marchandises ~s~ont été ~g~achetées ~s~par ton patron.',
        ['mission_dou_plants_abort'] = '~b~',
        ['mission_dou_plants_abort_2'] = '~s~s La mission a été ~r~annulée~s~, parce que tu n\'a pas assez d\'argent.',
        ['mission_dou_plants_abort_target'] = 'La mission a été ~r~annulée~s~, parce que les marchandises n\'ont pas été achetées.',
        ['mission_dou_plants_arrived'] = 'La livraison avec ~g~',
        ['mission_dou_plants_arrived_2'] = ' marchandises viennent d\'arriver.',
        ['mission_dou_plants_arrived_target'] = 'Marchandises ~g~livrées avec succès',

        ['mission_press_e_deliver'] = 'Appuie sur ~g~E~s~, pour décharger les marchandises',
        ['mission_wrongCar_deliver'] = 'Ce n\'est pas le véhicule qu\'on a chargé?',

        ['mission_invited'] = 'Tu as été ~g~invité ~s~à faire une ~b~mission~s~. Appuie sur  ~g~E~s~, pour accepter.',
        ['mission_invited_over'] = 'L\'invitation a ~r~expiré~s~!',

        ['menu_enter_farm'] = 'Entrer dans la ferme',
        ['menu_buy_farm'] = 'Acheter la ferme',
        ['menu_buy_name'] = 'Nom:',
        ['menu_buy_type'] = 'Type:',
        ['menu_buy_price'] = 'Prix:',
        ['menu_buy_confirm'] = 'Confirmer',

        ['menu_computer_level'] = 'Niveau ',
        ['menu_computer_produced'] = 'Drogues terminées',
        ['menu_computer_produced_desc'] = 'Drogues terminées et emballées',
        ['menu_computer_storage'] = 'Matières premières',
        ['menu_computer_storage_desc'] = 'Des matières premières sont nécéssaires à la production',
        ['menu_computer_takedrugs'] = 'Combien doit-être retiré?',
        ['menu_computer_notenoughdrugs'] = 'Tu n\'as pas autant en stock!',

        ['menu_storage'] = 'Obtenir des matières premières',
        ['menu_storage_input'] = 'Déposer matières premières',
        ['menu_storage_input_desc'] = 'Dépose les matières première que tu as dans ton inventaire',
        ['menu_storage_storageLimit'] = '~s~Il ne reste de la place que pour ~y~',
        ['menu_storage_storageLimit_2'] = ' matières premières~s~!',
        ['menu_storage_notenough'] = '~r~Tu n\'as pas assez de matières premières!',
        ['menu_storage_buy'] = 'Acheter des matières premières',
        ['menu_storage_buy_desc'] = 'Acheter des matières premières au marché noir',
        ['menu_storage_buy_self'] = 'Acheter des matières premières toi-même',
        ['menu_storage_buy_others'] = 'Laisser quelqu\'un acheter des matières premières',
        ['menu_storage_buy_others_desc'] = 'La personne doit rester à côté de l\'entrée de la ferme',
        ['menu_storage_inputseeds'] = 'Combien doit être déposé?',
        ['storagemission_invite'] = 'Clique pour inviter ~b~',
        ['storagemission_invite_2'] = '~s~',

        ['menu_upgrade'] = 'Upgrade la ferme',
        ['menu_upgrade_prod'] = 'Améliorer la ferme',
        ['menu_upgrade_prod_desc'] = 'Augmente la productivité et le stockage',
        ['menu_upgrade_prod_level2'] = 'Améliorer les équipements',
        ['menu_upgrade_prod_level2_desc'] = 'Augmente les performances en améliorant ton matériel. Exemple: meilleurs ventilateurs',
        ['menu_upgrade_prod_level3'] = 'Améliorer la sécurité',
        ['menu_upgrade_prod_level3_desc'] = 'Augmente tes performances en améliorant ta surveillance. Exemple: enregistrement vidéo',
        ['menu_upgrade_level2required'] = 'Niveau 2 réquis-+',
        ['upgraded_title'] = 'Acheter amélioration',
        ['upgraded'] = 'Le ~y~niveau ~s~de ta ferme a été augmenté jusqu\'à ~y~',
        ['upgraded_2'] = ' ~s~. Ré-entre dans la ferme pour voir les modifications.',

        ['menu_stats_finished'] = '~b~Capacité de stockage (drogues finies):',
        ['menu_stats_storecap'] = '~b~Capacité de stockage (matières premières):',
        ['menu_stats_storecap_desc'] = '~s~4x matières premières = 1x drogue',
        ['menu_stats_productivity'] = '~b~Vitesse de production',

        ['menu_changeVehicle'] = 'changer véhicule de mission',
        ['menu_changeVehicle_change'] = 'Clique pour sélectionner ~b~',
        ['menu_changeVehicle_change2'] = ' ~s~comme étant ton véhicule de mission',

        ['menu_access'] = 'Cartes d\'accès',
        ['menu_access_desc'] = 'Configure qui a accès à la ferme',
        ['menu_access_trust_remove'] = 'Clique pour révoquer ~b~',
        ['menu_access_trust_remove_2'] = ' ~s~s accès',
        ['menu_addTrusted'] = '~g~Donner l\'accès',
        ['menu_access_trust_add'] = 'Clique pour donner ~b~',
        ['menu_access_trust_add_2'] = ' ~s~l\'accès',

        ['menu_access_removed'] = ' ~s~s accès révoqué.',
        ['menu_access_removed_target'] = 'Votre accès à la ~y~ferme (#',
        ['menu_access_removed_target_2'] = ') a été révoqué.',
        ['menu_access_granted'] = ' ~s~s accès autorisé.',
        ['menu_access_granted_target'] = 'Tu as maintenant accès à la ~g~ferme (#',
        ['menu_access_granted_target_2'] = ')',
    },

    -- CAR 

    ['fr'] = {
        ['ring_infobar'] = 'Press ~b~E~s~ to notify a cardealer',
        ['showroom_infobar'] = 'Press ~b~E~w~, to access the ~o~Showroom~w~!',
        ['boss_infobar'] = 'Press ~b~E~w~, to access the ~o~Boss Menü~w~!',
        ['wardrobe_infobar'] = 'Press ~b~E~w~, to access the ~o~wardrobe~w~!',
        ['garage_infobar'] = 'Press ~b~E~w~, to access the ~o~garage~w~!',
        ['computer_infobar'] = 'Press ~b~E~w~, to access the ~o~Computer~w~!',
        ['delete_vehicle'] = 'Press ~b~E~w~, to ~o~store the vehicle~w~!',
        ['wardrobe'] = 'Wardrobe',
        ['private_clothes'] = 'Private clothes',
        ['bossmenu'] = 'Boss Menu',
        ['finance_management'] = 'Financial management',
        ['staff'] = 'Staff management',
        ['society_money'] = 'Society money',
        ['withdraw_money'] = 'Withdraw money',
        ['deposit_money'] = 'Deposit money',
        ['withdraw_desc'] = 'Do you want to ~g~withdraw~w~ money?',
        ['deposit_desc'] = 'Do you want to ~g~deposit~w~ money?',
        ['how_much'] = 'How much?',
        ['company_money'] = 'Society money',
        ['unknown_amount'] = '~r~Invlaid amount!',
        ['deposit_msg'] = 'You deposited ~g~',
        ['deposit_msg2'] = ' $~w~',
        ['withdraw_msg'] = 'You have withdrawn ~g~',
        ['withdraw_msg2'] = ' $~w~ from your society',
        ['hire'] = 'Hire somebody',
        ['staff_management'] = 'Staff management',
        ['job_rank'] = 'Job rank:',
        ['fire'] = '~r~Fire',
        ['fire_msg'] = 'Do you want to fire ~b~',
        ['fire_msg2'] = '~w~?',
        ['promote'] = 'Promote',
        ['promote_msg'] = 'Do you want to promote ~b~',
        ['promote_msg2'] = '~w~ to ~b~',
        ['promote_msg3'] = ' ~w~?',
        ['showroom'] = 'Showroom',
        ['change_color'] = '~b~Change color',
        ['primary_color'] = 'Primary color',
        ['primary_color_msg'] = 'Set as primary color',
        ['secondary_color'] = 'Secondary color',
        ['secondary_color_msg'] = 'Set as secondary color',
        ['pearl'] = 'Pearlescent',
        ['pearl_msg'] = 'Set as pearlescent',
        ['show_manufacturer'] = 'Manufacturer:',
        ['show_price'] = 'Price:',
        ['show_model'] = 'Model:',
        ['show_park_item'] = 'Exhibit at Showroom',
        ['show_performance'] = 'Performance:',
        ['show_maxSpeed'] = 'Max. speed:',
        ['show_speedup'] = 'Speedup 0-100:',
        ['show_modifications'] = 'Amount of modifications:',
        ['show_fuelcapacity'] = 'Fuel capacity:',
        ['show_suffix_performance'] = ' PS',
        ['show_suffix_maxSpeed'] = ' mp/h',
        ['show_suffix_speedup'] = ' seconds',
        ['show_suffix_modifications'] = ' parts',
        ['show_suffix_fuelcapacity'] = ' l',
        ['test_drive'] = '~b~Prepare for a test drive',
        --['amount_cardealer'] = 'Stock in cardealership:',
        ['amount_storage'] = 'Stock in warehouse:',
        ['set_to_showroom'] = 'Exhibit at Showroom',
        ['amount_cars'] = 'Cars available',
        ['computer'] = 'Computer',
        ['sell_vehicle'] = 'Sell vehicle',
        ['show_1'] = 'Showroom 1',
        ['show_2'] = 'Showroom 2',
        ['show_3'] = 'Showroom 3',
        ['show_4'] = 'Showroom 4',
        ['show_abort'] = '~r~Abort',
        ['yes'] = 'Yes',
        ['no'] = 'No',
        ['car_sell'] = ' (Press to sell)',
        ['bill_purchase_of'] = 'Purchase of a ',
        ['dialog_price'] = 'Price',
        ['no_customers'] = '~o~There is no customer next to you! There have to be a customer next to you to sell a car.',
        ['vehicles_list'] = 'Vehicles',
        --['car_deliver'] = 'Bring this car to the dealership: ',
        ['car_craft'] = 'Order this vehicle: ',
        ['amount'] = 'Amount',
        --['ordered'] = 'Ordered: ',
        ['reserved'] = 'Ordered: ',
        ['orders'] = 'Orders',
        ['total_production_time'] = 'Remaining production time:',
        ['current_production_time'] = 'Ordered vehicles:',
        ['refresh_time'] = 'Refresh',
        ['hours'] = ' hours',
        ['hired'] = '~g~Hired~w~!',
        ['you_were_hired'] = 'You were ~g~hired!~w~',
        ['you_hired'] = 'You ~g~hired ~b~',
        ['you_hired2'] = '~g~~w~!',
        ['already_hired'] = '~r~Already hired!~w~',
        ['is_already_hired'] = ' is already ~r~hired~w~!',
        ['fired'] = '~r~Fired~w~!',
        ['you_are_fired'] = 'You were ~r~fired~w~!',
        ['you_fired'] = 'You ~r~fired ~b~',
        ['you_fired2'] = '~r~~w~!',
        ['error'] = '~r~Error~w~!',
        ['player_not_online'] = 'This ~b~player~w~ is not online!',
        ['promoted'] = '~g~Promoted~w~!',
        ['you_were_promoted'] = 'You were ~b~promoted ~s~to~b~',
        ['you_were_promoted2'] = '~g~~w~!',
        ['you_promoted'] = 'You ~b~promoted ~b~',
        ['you_promoted2'] = '~w~ to ~b~',
        ['you_promoted3'] = '~g~~w~!',
        ['ring_ring'] = '~b~There is a ~w~customer waiting ~b~at the dealership!',
        ['vehicle_purchased'] = '~g~Vehicle purchased~w~!',
        ['you_purchased'] = 'You got a ',
        ['you_purchased2'] = ', with the number plate ',
        ['you_purchased3'] = ' ~g~',
        ['vehicle_sold'] = '~g~Vehicle sold~w~!',
        ['you_sold'] = 'You sold a ',
        ['you_sold2'] = ' ~g~',
        ['vehicle_ordered'] = '~g~Vehicle ordered~w~!',
        ['you_ordered'] = 'You ~g~ordered ',
        ['you_ordered2'] = ' ~s~. In total you ~g~ordered ',
        ['you_ordered3'] = 'x ~s~!',
        ['you_applied'] = 'You ~g~ordered ',
        ['you_applied2'] = ' ~s~. In total you ~g~ordered ',
        ['you_applied3'] = '~s~.',
        ['not_enough_money'] = 'There is ~r~not enough money~s~ on your society wallet!',
        ['vehicle_delivered'] = 'Vehicles ~g~successfully delivered~s~!',
        ['not_enough_vehicles_in_storage'] = 'There are not enough vehicles in the large warehouse',
        ['presented_prefix'] = '~y~Displayed: ~s~',
        ['insert_new_value'] = 'Insert a new value',
        ['click_to_change'] = '~b~click to change the value',
        ['not_enough_money_player'] = '~r~Not enough money!',
        ['required_order_time'] = 'Required manufacturing time:',
		['customer_not_enough_money'] = '~r~The customer does not have enough money!',
    },

}